// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhggndsvjpegeqifbgii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZ2duZHN2anBlZ2VxaWZiZ2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjQ1NDUsImV4cCI6MjA3MDIwMDU0NX0.HILXZim1DLKSS0_kA11mi3aEVpZkPEUcsTcxI1mNrUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});